# Numpy Array Creation

In [14]:
#NumPy.empty
'''Syntax : - numpy.empty(shape, dtype = float, order = 'C')'''

import numpy as np
a = np.empty((3,2), dtype=int, order='F') #The default order is the c-style row-major order. It can be set to F for FORTRAN-style column-major order
print(a)

[[6422645 7274612]
 [6619204 6029424]
 [7012467 6881378]]


In [16]:
#NumPy.Zeros
import numpy as np
a = np.zeros((3,2), dtype=int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [22]:
#NumPy.Ones
import numpy as np
a = np.ones((3,2), dtype=int)
print(a)

[[1 1]
 [1 1]
 [1 1]]


***Numpy array from existing data***

In [30]:
#numpy.asarray
'''This routine is used to create an array by using the existing data in the form of lists, or tuples. This routine is useful in the scenario where we need to convert a python sequence into the numpy array object'''

import numpy as np
l = [1,2,3,4,5,6]
t = (1,2,3,4,5,6)
arr = [[1,2,3,4],
      [5,6]]
a = np.asarray(l)
b = np.asarray(t)
c = np.asarray(arr)
print("---------------------------------------------------")
print()
print('creating numpy array using the list')
print(type(a))
print(a)
print()
print("---------------------------------------------------")
print()

print('creating a numpy array using Tuple')
print(type(b))
print(b)
print()
print("---------------------------------------------------")
print()

print('creating a numpy array using more than one list')
print(type(c))
print(c)
print()
print("---------------------------------------------------")
print()

---------------------------------------------------

creating numpy array using the list
<class 'numpy.ndarray'>
[1 2 3 4 5 6]

---------------------------------------------------

creating a numpy array using Tuple
<class 'numpy.ndarray'>
[1 2 3 4 5 6]

---------------------------------------------------

creating a numpy array using more than one list
<class 'numpy.ndarray'>
[list([1, 2, 3, 4]) list([5, 6])]

---------------------------------------------------



In [36]:
#numpy.frombuffer
'''This function is used to create an array by using the specified buffer. The syntax to use this buffer is given below'''

import numpy as np
l = b'Hello World'
print(type(l))

a = np.frombuffer(l, dtype='S1')
print(a)
print(type(a))

<class 'bytes'>
[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [39]:
#numpy.fromiter
'''This routine is used to create a ndarray by using an iterable object. It returns a one-dimensional ndarray object'''

import numpy as np
list = [1,2,3,4]
a = np.fromiter(list, dtype=float)
print(a)

[1. 2. 3. 4.]


***Numpy Arrays within the numerical range***

In [51]:
#Numpy.arrange
'''Syntax : - numpy.arrange(start, stop, step, dtype) '''

import numpy as np
a = np.arange(1,11,2,float)
print(a)

b = np.arange(1,100,5,int)
print(b)

[1. 3. 5. 7. 9.]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [61]:
#NumPy.linspace
'''It is similar to the arrange function. However, it doesn?t allow us to specify the step size in the syntax.
Syntax : - numpy.linspace(start, stop, num, endpoint, retstep, dtype)   '''

import numpy as np
a = np.linspace(1,10,5)
print(a)

print()

arr = np.linspace(10, 20, 5, endpoint = False)  
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]

[10. 12. 14. 16. 18.]


In [64]:
#numpy.logspace
'''
It creates an array by using the numbers that are evenly separated on a log scale.

The syntax is given below.
numpy.logspace(start, stop, num, endpoint, base, dtype)

It accepts the following parameters.

- start:    It represents the starting value of the interval in the base.
- stop:     It represents the stopping value of the interval in the base.
- num:      The number of values between the range.
- endpoint: It is a boolean type value. It makes the value represented by stop as the last value of the interval.
- base:     It represents the base of the log space.
- dtype:    It represents the data type of the array items.
'''

import numpy as np
a = np.logspace(10,20,num=5, endpoint=True)
print(a)

print()

arr = np.logspace(10, 20, num = 5,base = 2, endpoint = True)  
print(arr)  

[1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]

[1.02400000e+03 5.79261875e+03 3.27680000e+04 1.85363800e+05
 1.04857600e+06]


In [ ]:
                                                    #NumPy Broadcasting

In [5]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([8,9,1,2,3,4])
print(a+b)
print()
print(a*b)

[ 9 11  4  6  8 10]

[ 8 18  3  8 15 24]


In [9]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
b = np.array([2,4,6,8])

print("\nArray A:\n",a)
print("\nArray B:\n",b)
print("\nAddition Of Array A And B:\n",a*b)


Array A:
 [[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

Array B:
 [2 4 6 8]

Addition Of Array A And B:
 [[ 2  8 18 32]
 [10 24 42 64]
 [18  0  6 16]]


In [ ]:
                                            #NumPy Array Iteration

In [19]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,0,4,5]])
print(a)

print()

for i in np.nditer(a):
    print(i, end=' ')

[[1 2 3 4]
 [5 6 7 8]
 [9 0 4 5]]

1 2 3 4 5 6 7 8 9 0 4 5 

In [49]:
#Array Values Modification
'''We can not modify the array elements during the iteration since the op-flag associated with the Iterator object is set to readonly.

However, we can set this flag to readwrite or write only to modify the array values. Consider the following example'''

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 3 * x
    print(x, end=' ')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3 6 9 12 15 18 21 24 27 

In [ ]:
                                            #NumPy Bitwise Operators

In [41]:
import numpy as np
a = 12
b = 10
print("Binary Representation Of a:",bin(a))
print("Binary Representation Of b:",bin(b))
print("Bitwise-and of a and b:",np.bitwise_and(a,b))
print("Bitwise-or of a and b:",np.bitwise_or(a,b))

Binary Representation Of a: 0b1100
Binary Representation Of b: 0b1010
Bitwise-and of a and b: 8
Bitwise-or of a and b: 14


In [44]:
import numpy as np
arr = np.array([20],dtype="uint8")
print("Binary Repersentation:", np.binary_repr(20,8))
print(np.invert(arr))
print("Binary Repersentation:", np.binary_repr(235,8))

Binary Repersentation: 00010100
[235]
Binary Repersentation: 11101011


In [45]:
import numpy as np
print("Left side of 20 by 3 bits",np.left_shift(20,3))
print("Binary Representation of 20 in 8 bits",np.binary_repr(20,8))
print("Binary Representation of 160 in 8 bits",np.binary_repr(160,8))

Left side of 20 by 3 bits 160
Binary Representation of 20 in 8 bits 00010100
Binary Representation of 160 in 8 bits 10100000


In [46]:
import numpy as np
print("Right side of 20 by 3 bits",np.right_shift(20,3))
print("Binary Representation of 160 in 8 bits",np.binary_repr(20,8))
print("Binary Representation of 160 in 8 bits",np.binary_repr(160,8))

Right side of 20 by 3 bits 2
Binary Representation of 160 in 8 bits 00010100
Binary Representation of 160 in 8 bits 10100000


In [ ]:
                                                #NumPy String Functions

In [69]:
import numpy as np
print("Concatenating Two Array Strings")
print(np.char.add(['Welcome To ','Thanks '],['Machine Learning Tutorials','JavaTPoint']))
print()
print(np.char.multiply('Hello ',3))
print()
print(np.char.center("Javatpoint",20,'*'))
print()
print(np.char.capitalize("welcome to javatpoint"))
print()
print(np.char.title("welcome to machine learning"))
print()
print(np.char.lower("WELCOME TO JAVATPOINT"))
print()
print(np.char.upper("welcome to machine learning"))
print()
print(np.char.split("welcome to machine learning",sep=" "))
print()
print(np.char.splitlines("welcome\nto\nmachine\nlearning"))


Concatenating Two Array Strings
['Welcome To Machine Learning Tutorials' 'Thanks JavaTPoint']

Hello Hello Hello 

*****Javatpoint*****

Welcome to javatpoint

Welcome To Machine Learning

welcome to javatpoint

WELCOME TO MACHINE LEARNING

['welcome', 'to', 'machine', 'learning']

['welcome', 'to', 'machine', 'learning']


In [73]:
import numpy as np
str = "    Welcome to javatpoint     "
print("\nOriginal String:", str)
print()
print("Removing the whitelabes, leading and trailing from string\n")
print(np.char.strip(str))


Original String:     Welcome to javatpoint     

Removing the whitelabes, leading and trailing from string

Welcome to javatpoint


In [76]:
import numpy as np
print(np.char.join(':','HMdf'))

H:M:d:f


In [80]:
import numpy as np
str = "welcome tojavatpoint"
print("\nOriginal String:",str)
print()
print(np.char.replace(str,"welcome to","www."))


Original String: welcome tojavatpoint

www.javatpoint


In [82]:
import numpy as np
estr = np.char.encode("Python Is Best Programming Language For Machine Learning","cp500")
dstr = np.char.decode(estr,"cp500")
print(estr,"\n")
print(dstr)

b'\xd7\xa8\xa3\x88\x96\x95@\xc9\xa2@\xc2\x85\xa2\xa3@\xd7\x99\x96\x87\x99\x81\x94\x94\x89\x95\x87@\xd3\x81\x95\x87\xa4\x81\x87\x85@\xc6\x96\x99@\xd4\x81\x83\x88\x89\x95\x85@\xd3\x85\x81\x99\x95\x89\x95\x87' 

Python Is Best Programming Language For Machine Learning


In [ ]:
                                            #NumPy Mathematical Functions

In [3]:
import numpy as np
arr = [0,30,60,120,150,180]
print("\nThe sin value of angles", end=' ')
print(np.sin(arr*np.pi/180))  
print()

print("\nThe cos value of angles", end=' ')
print(np.cos(arr*np.pi/180))
print()

print("\nThe tan value of angles", end=' ')
print(np.tan(arr*np.pi/180))
print()


The sin value of angles 

TypeError: can't multiply sequence by non-int of type 'float'

In [94]:
#Rounding Functions
import numpy as np
arr =  np.array([12.7654,1.234567,6.9876543,468.2])
print(arr)
print()
print("Array Round Off:",np.around(arr))
print("Array Valuse Rounded Off 2 Postion:",np.around(arr,2))
print("Array Valuse Rounded Off -1 Postion:",np.around(arr,-1))

[ 12.7654      1.234567    6.9876543 468.2      ]

Array Round Off: [ 13.   1.   7. 468.]
Array Valuse Rounded Off 2 Postion: [ 12.77   1.23   6.99 468.2 ]
Array Valuse Rounded Off -1 Postion: [ 10.   0.  10. 470.]


In [95]:
import numpy as np
arr = np.array([12.8765423,45.234,0.23467])
print(np.floor(arr))

[12. 45.  0.]


In [98]:
import numpy as np
arr = np.array([12.202,58.679,7.38672])
print(np.ceil(arr))

[13. 59.  8.]


In [27]:
import numpy as np

arr = np.array([0,30,60,90])
print("Printing the sin valuse of different angles")
sinval = np.sin(arr*np.pi/180)
print(sinval)
print("\nPrinting inverse of sin")
cosec = np.arcsin(sinval)
print(cosec)
print("\nPrinting the values in degrees")
print(np.degrees(cosec))

print("\n\n\nPrinting the values of cos with different angles")
cos = np.cos(arr*np.pi/180)
print(cos)
print("\nPrinting inverse of cos")
sec = np.arccos(cos)
print(sec)
print("\nPrinting the values in degrees")
print(np.degrees(sec))

print("\n\n\nPrinting the values of tan with different angles")
tan = np.tan(arr*np.pi/180)
print(tan)
print("\nPrinting inverse of tan")
cot = np.arctan(tan)
print(cot)
print("\nPrinting the values of tan in degrees")
print(np.degrees(cot))

Printing the sin valuse of different angles
[0.        0.5       0.8660254 1.       ]

Printing inverse of sin
[0.         0.52359878 1.04719755 1.57079633]

Printing the values in degrees
[ 0. 30. 60. 90.]



Printing the values of cos with different angles
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]

Printing inverse of cos
[0.         0.52359878 1.04719755 1.57079633]

Printing the values in degrees
[ 0. 30. 60. 90.]



Printing the values of tan with different angles
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]

Printing inverse of tan
[0.         0.52359878 1.04719755 1.57079633]

Printing the values of tan in degrees
[ 0. 30. 60. 90.]


In [ ]:
                                            #Numpy statistical functions

In [38]:
import numpy as np  
  
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("The original array:\n")  
print(a)  
  
  
print("\nThe minimum element among the array:",np.amin(a))  
print("The maximum element among the array:",np.amax(a))  
  
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("The maximum element among the rows of array",np.amax(a,0))  
  
print("\nThe minimum element among the columns of array",np.amin(a,1))  
print("The maximum element among the columns of array",np.amax(a,1))  

The original array:

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2
The maximum element among the array: 80

The minimum element among the rows of array [ 2 10 10]
The maximum element among the rows of array [80 43 31]

The minimum element among the columns of array [ 2 31 10]
The maximum element among the columns of array [20 80 43]


In [39]:
#numpy.ptp()
'''The name of the function numpy.ptp() is derived from the name peak-to-peak. It is used to return the range of values along an axis.'''

import numpy as np  
  
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("Original array:\n",a)  
  
print("\nptp value along axis 1:",np.ptp(a,1))  
  
print("ptp value along axis 0:",np.ptp(a,0))      

Original array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


In [121]:
import numpy as np  
  
a = np.array([[1,2,3],[1,2,3]])  
  
print("Array:\n",a)  
  
print("\nPercentile along axis 0",np.percentile(a, 10,0))  
  
print("Percentile along axis 1",np.percentile(a, 10, 1))  

Array:
 [[1 2 3]
 [1 2 3]]

Percentile along axis 0 [1. 2. 3.]
Percentile along axis 1 [1.2 1.2]


In [58]:
import numpy as np  
  
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
  
print("Array:\n",a)  
  
print("\nMedian of array along axis 0:",np.median(a,0))  
print("Mean of array along axis 0:",np.mean(a,0))  
print("Average of array along axis 1:",np.average(a,1))  

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]
Mean of array along axis 0: [4. 5. 6.]
Average of array along axis 1: [2. 5. 8.]


In [76]:
import numpy as np  
  
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
print(a)

print("\nSorting along the columns")
print(np.sort(a))

print("\nSorting along the rows")
print(np.sort(a,0))

print("\nSorting by names")
data_type = np.dtype([('name','S10'),('marks',int)])
arr = np.array([('Mukesh',100),('John',100)],dtype=data_type)
print(np.sort(arr, order='name'))

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]

Sorting along the columns
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]

Sorting along the rows
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]

Sorting by names
[(b'John', 100) (b'Mukesh', 100)]


In [93]:
#numpy.argsort()
import numpy as np

a = np.array([111,22,56,60,38])
print("Original Array:\n", a)

print()

sort_ind = np.argsort(a)
print("Printing indices of sorted data\n",sort_ind)

print()

sort_a = a[sort_ind]
print("Printing sorted array")

for i in sort_ind:
    print(a[i],end=" ")

Original Array:
 [111  22  56  60  38]

Printing indices of sorted data
 [1 4 2 3 0]

Printing sorted array
22 38 56 60 111 

In [96]:
#numpy.lexsort() 
import numpy as np

a = np.array(['a','b','c','d','e'])
b = np.array([123,345,65,35,3])

ind = np.lexsort((a,b))
print("Printing indices of sorted data\n",ind)

print("Using the indices to sort the array")
for i in ind:
    print(a[i],b[i])

Printing indices of sorted data
 [4 3 2 0 1]
Using the indices to sort the array
e 3
d 35
c 65
a 123
b 345


In [106]:
#numpy.nonzero()

import numpy as np

a = np.array([1,5,64,84,0,3,0])
print("Original Array:\n",a)

print("Printing location of the non-zero elements\n")
print("First Method")
print(np.nonzero(a))
print("Second Method")
print(a.nonzero())

Original Array:
 [ 1  5 64 84  0  3  0]
Printing location of the non-zero elements

First Method
(array([0, 1, 2, 3, 5], dtype=int64),)
Second Method
(array([0, 1, 2, 3, 5], dtype=int64),)


In [120]:
#numpy.where()
'''This function is used to return the indices of all the elements which satisfies a particular condition.
'''

import numpy as np

a = np.array([4,1,3,8,6,45])
print(np.where(a>2))

b = np.array([[1,2,3],[4,5,6]])
print(np.where(b>2))

(array([0, 2, 3, 4, 5], dtype=int64),)
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [ ]:
                                            #NumPy Copies and Views

In [135]:
import numpy as np
a = np.array([[12,34,65,34],[43,8,9,7,],[98,56,32,87]])
print("Original Array:\n",a)

print("\nId of array a:",id(a))

b = a

print("\nMaking copy of array a")
print("\nId of b",id(b))

b.shape = 4,3

print("\nChanges on b also reflect to a:")
print(a)

Original Array:
 [[12 34 65 34]
 [43  8  9  7]
 [98 56 32 87]]

Id of array a: 2305083759312

Making copy of array a

Id of b 2305083759312

Changes on b also reflect to a:
[[12 34 65]
 [34 43  8]
 [ 9  7 98]
 [56 32 87]]


In [138]:
#ndarray.view()

import numpy as np
a = np.array([[12,34,65,34],[43,8,9,7,],[98,56,32,87]])
print("Original Array:\n",a)

print("\nId of array a:",id(a))

b = a.view()
print("\nId of b",id(b))
print("\nPrinting the view of b")
print(b)

b.shape = 4,3

print("\nChanges on b do not reflect to a:")
print("\nOriginal Array\n",a)
print("\nView\n",b)

Original Array:
 [[12 34 65 34]
 [43  8  9  7]
 [98 56 32 87]]

Id of array a: 2305061555776

Id of b 2305083562864

Printing the view of b
[[12 34 65 34]
 [43  8  9  7]
 [98 56 32 87]]

Changes on b do not reflect to a:

Original Array
 [[12 34 65 34]
 [43  8  9  7]
 [98 56 32 87]]

View
 [[12 34 65]
 [34 43  8]
 [ 9  7 98]
 [56 32 87]]


In [139]:
#ndarray.copy()

import numpy as np
a = np.array([[12,34,65,34],[43,8,9,7,],[98,56,32,87]])
print("Original Array:\n",a)

print("\nId of array a:",id(a))

b = a.copy()
print("\nId of b",id(b))
print("\nPrinting the deep copy of b")
print(b)

b.shape = 4,3

print("\nChanges on b do not reflect to a:")
print("\nOriginal Array\n",a)
print("\nView\n",b)

Original Array:
 [[12 34 65 34]
 [43  8  9  7]
 [98 56 32 87]]

Id of array a: 2305090691600

Id of b 2305083519584

Printing the deep copy of b
[[12 34 65 34]
 [43  8  9  7]
 [98 56 32 87]]

Changes on b do not reflect to a:

Original Array
 [[12 34 65 34]
 [43  8  9  7]
 [98 56 32 87]]

View
 [[12 34 65]
 [34 43  8]
 [ 9  7 98]
 [56 32 87]]


In [ ]:
                                                    #NumPy Matrix Library

In [42]:
import numpy as np  
import numpy.matlib 

print(np.matlib.empty((3,3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
import numpy as np
import numpy.matlib

print(np.matlib.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
import numpy as np
import numpy.matlib

print(np.matlib.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
#numpy.matlib.eye() function :-- This function returns a matrix with the diagonal elements initialized to 1 and zero elsewhere.
'''
n:     It represents the number of rows in the resulting matrix.
M:     It represents the number of columns, defaults to n.
k:     It is the index of diagonal.
dtype: It is the data type of the output
'''

import numpy as np
import numpy.matlib

print(np.matlib.eye(n=5,M=5,k=0,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [37]:
#numpy.matlib.identity() function
'''This function is used to return an identity matrix of the given size. 
An identity matrix is the one with diagonal elements initializes to 1 and all other elements to zero.'''

import numpy as np
import numpy.matlib

print(np.matlib.identity(3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [44]:
import numpy as np
import numpy.matlib

print(np.matlib.rand(3,2))

[[0.22015935 0.31587108]
 [0.42869691 0.14678804]
 [0.7645049  0.85118075]]


In [ ]:
                                                    #NumPy Linear Algebra

In [47]:
#numpy.dot() function
'''This function is used to return the dot product of the two matrices. It is similar to the matrix multiplication.

The dot product is calculated as:   [100 * 10 + 200 * 12, 100 * 20 + 200 * 21] [23*10+12*12, 23*20 + 12*21] 
'''

import numpy as np

a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)

[[3400 6200]
 [ 374  712]]


In [48]:
import numpy as np

a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)

5528


In [50]:
import numpy as np

a = np.array([100,200])  
b = np.array([10,20])  
inner = np.inner(a,b)  
print(inner)

5000


In [52]:
import numpy as np  

a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)
print(mul)

[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


In [53]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [54]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(np.linalg.solve(a,b))

[[1. 0.]
 [0. 1.]]


In [57]:
import numpy as np

a = np.array([[1,2],[3,4]])
print("\nOriginal Array:\n",a)
b = np.linalg.inv(a)
print("Inverse:\n",b)


Original Array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
                                            #NumPy Matrix Multiplication

In [65]:
#Element-wise matrix multiplication
import numpy as np

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
array2 = np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)
result = np.multiply(array1,array2)
print(result)

[[[ 9 16 21]
  [24 25 24]
  [21 16  9]]]


In [62]:
#Matrix product
import numpy as np  

array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result = np.matmul(array1,array2)
print(result)

[[[ 30  24  18]
  [ 84  69  54]
  [138 114  90]]]


In [66]:
import numpy as np

array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result = np.dot(array1,array2)
print(result)

[[[[ 30  24  18]]

  [[ 84  69  54]]

  [[138 114  90]]]]
