In [5]:
# Q. Import numpy as np and print the version number.
import numpy as np
print(np.__version__)

1.18.5


In [10]:
# Q. Create a 1D array of numbers from 0 to 9
import numpy as np
n = np.arange(0,10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# Q. Create a 3×3 numpy array of all True’s
import numpy as np
n = np.full((3,3), True,dtype=bool)
print(n)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [48]:
# Q. Extract all odd numbers from arr
import numpy as np
import numpy.matlib
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

#1 Method
for i in a:
    for j in i:
        if j%2 != 0:
            print("{} is odd number".format(j))
#2 Method
print(a[a%2 ==1])

1 is odd number
3 is odd number
5 is odd number
7 is odd number
9 is odd number
[1 3 5 7 9]


In [87]:
# Q. Replace all odd numbers in arr with -1                         
import numpy as np
import numpy.matlib
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a[a%2==1] = -1
print(a)


[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [103]:
# Q. Replace all odd numbers in arr with -1 without changing arr
import numpy as np
import numpy.matlib
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Array\n",a)

out = np.where(a%2==1,-1,a)
print("Changes In Original Array\n",out)
print("Original Array\n",a)

# b = a.view()
# b[b%2==1] = -1
# print("\nChages In B\n",b)
# print("\nChanges In B Does Not Reflect On A\n",a)


Original Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Changes In Original Array
 [[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]
Original Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
# Q. Convert a 1D array to a 2D array with 2 rows
import numpy as np
a = np.arange(0,10)

newarr1 = a.reshape(2,5)
print("Method 1\n",newarr)

newarr2 = a.reshape(2,-1)                 # Setting to -1 automatically decides the number of cols
print("Method 2\n",newarr2)

Method 1
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Method 2
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [156]:
# Q. Stack arrays a and b vertically
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
med1 = np.concatenate((a,b))
print("Method 1\n",med1)

med2 = np.vstack((a,b))
print("Method 2\n",med2)

med3 = np.r_[a,b]
print("Method 3\n",med3)

Method 1
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Method 2
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Method 3
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [160]:
# Q. Stack the arrays a and b horizontally.

med1 = np.concatenate((a,b),axis=1)
print("Method 1\n",med1)

med2 = np.hstack((a,b))
print("Method 2\n",med2)

med3 = np.c_[a,b]
print("Method 3\n",med3)

Method 1
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Method 2
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Method 3
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [26]:
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
import numpy as np
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [56]:
# Q. Get the common items between a and b
import numpy as np

a = np.arange(1,10)
b = np.arange(4,12)
np.intersect1d(a,b)    

array([4, 5, 6, 7, 8, 9])

In [59]:
# Q. From array a remove all items present in array b
import numpy as np

a = np.arange(1,10)
b = np.arange(4,12)
np.setdiff1d(a,b)

array([1, 2, 3])

In [100]:
# Q. Get the positions where elements of a and b match
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)
#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)

In [118]:
# Q. Get all items between 5 and 10 from a.

a = np.arange(10)
print(a)
print()

index = np.where((a>=5) & (a<=10))
print("Method 1:",index)
print()

ans = np.where(np.logical_and(a>=5,a<=10))
print("Method 2:",ans)
print()


print("Method 3:",a[(a>=5) & (a<=10)])
print()

[0 1 2 3 4 5 6 7 8 9]

Method 1: (array([5, 6, 7, 8, 9], dtype=int64),)

Method 2: (array([5, 6, 7, 8, 9], dtype=int64),)

Method 3: [5 6 7 8 9]



In [1]:
# Q. Convert the function maxx that works on two scalars, to work on two arrays.
import numpy as np
def maxx(x,y):
    if x >= y:
        return x
    else:
        return y

maxx = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
maxx(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [24]:
# Q. Swap columns 1 and 2 in the array arr.

import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [29]:
# Q. Swap rows 1 and 2 in the array arr:

import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,0,2],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [54]:
# Q. Reverse the rows of a 2D array arr.
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
print("\nFirst Method")
print(arr[[2,1,0],:])

print("\nSecond Method")
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

First Method
[[6 7 8]
 [3 4 5]
 [0 1 2]]

Second Method
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [59]:
# Q. Reverse the columns of a 2D array arr.
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)
print("\nFirst Method")
print(arr[:,[2,1,0]])

print("\nSecond Method")
print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

First Method
[[2 1 0]
 [5 4 3]
 [8 7 6]]

Second Method
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [77]:
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
import numpy as np
a = np.random.randint(low=5,high=10,size=(5,3))
print("Method One\n",a)

b = np.random.uniform(low=5,high=10,size=(5,3))
print("\nMethod Second\n",b)

Method One
 [[8 9 7]
 [5 7 9]
 [7 8 5]
 [5 6 9]
 [7 6 9]]

Method Second
 [[7.75836966 6.90741533 7.94462252]
 [5.26696323 9.89180304 5.13235185]
 [9.43313275 7.08084506 9.64978995]
 [8.3027531  8.61343451 7.06134636]
 [6.94334733 9.19440532 9.80175514]]


In [86]:
# Q. Print or show only 3 decimal places of the numpy array rand_arr.
import numpy as np
a = np.random.uniform(low=5,high=10,size=(5,3))
np.set_printoptions(precision=3)
a[:4]

array([[6.08 , 9.524, 6.247],
       [5.441, 7.596, 7.144],
       [5.566, 8.877, 9.454],
       [6.456, 9.899, 5.764]])

In [120]:
# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
import numpy as np
rand_arr = np.random.uniform(low=5,high=10,size=(5,3))/1e1
np.set_printoptions(suppress=True,precision=3)
print(rand_arr)

[[0.741 0.892 0.738]
 [0.619 0.726 0.637]
 [0.944 1.    0.74 ]
 [0.968 0.572 0.846]
 [0.503 0.52  0.735]]


In [134]:
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
import numpy as np
a = np.arange(23)
np.set_printoptions(threshold=21)
print(a)

[ 0  1  2 ... 20 21 22]


In [150]:
#Q. Import the iris dataset keeping the text intact.
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa']], dtype=object)

In [9]:
# Q. Extract the text column species from the 1D iris imported in previous question.
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

print(iris_1d.shape)

species = np.array([row[4] for row in iris_1d])
print(species[:5])

(150,)
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


<ipython-input-9-2aa9760d3698>:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
